// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: equipment_categories
// Endpoint: equipment-categories
// API Name: Category
// LC API Name: category
// API Class: CategoryDetail

package equipment_categories

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	categoryClient struct {
		api.BasicsProvider
		uri string
	}
)

type CategoryClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*CategoryDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) CategoryClient {
	return &categoryClient{
		BasicsProvider: basicsProvider,
		uri: "/equipment-categories",
	}
}

func (ac *categoryClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *categoryClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *categoryClient) GetByIndex(index string) (*CategoryDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := CategoryDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
