// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: conditions
// Endpoint: conditions
// API Name: Condition
// LC API Name: condition
// API Class: api.Description

package conditions

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	conditionClient struct {
		api.BasicsProvider
		uri string
	}
)

type ConditionClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*api.Description, error)
}

func NewClient(basicsProvider api.BasicsProvider) ConditionClient {
	return &conditionClient{
		BasicsProvider: basicsProvider,
		uri: "/conditions",
	}
}

func (ac *conditionClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *conditionClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *conditionClient) GetByIndex(index string) (*api.Description, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := api.Description{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
