// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: conditions
// Endpoint: conditions
// API Name: Condition
// LC API Name: condition
// API Class: api.Description

package conditions

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/conditions"
	ChildEndpoint = Endpoint + "/"
)

type (
	conditionClient struct {
		basicsProvider api.BasicsProvider
	}
)

type ConditionClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*api.Description, error)
}

func NewClient(basicsProvider api.BasicsProvider) ConditionClient {
	return &conditionClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *conditionClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *conditionClient) GetByIndex(index string) (*api.Description, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := api.Description{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
