// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: categories
// Endpoint: categories
// API Name: Category
// LC API Name: category
// API Class: CategoryDetail

package categories

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/categories"
	ChildEndpoint = Endpoint + "/"
)

type (
	categoryClient struct {
		basicsProvider api.BasicsProvider
	}
)

type CategoryClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*CategoryDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) CategoryClient {
	return &categoryClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *categoryClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *categoryClient) GetByIndex(index string) (*CategoryDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := CategoryDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
