// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: spellcasting
// Endpoint: spellcasting
// API Name: Spellcasting
// LC API Name: spellcasting
// API Class: SpellcastingDetail

package spellcasting

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	spellcastingClient struct {
		api.BasicsProvider
		uri string
	}
)

type SpellcastingClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*SpellcastingDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SpellcastingClient {
	return &spellcastingClient{
		BasicsProvider: basicsProvider,
		uri: "/spellcasting",
	}
}

func (ac *spellcastingClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *spellcastingClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *spellcastingClient) GetByIndex(index string) (*SpellcastingDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := SpellcastingDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
