// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: spellcasting
// Endpoint: spellcasting
// API Name: Spellcasting
// LC API Name: spellcasting
// API Class: SpellcastingDetail

package spellcasting

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/spellcasting"
	ChildEndpoint = Endpoint + "/"
)

type (
	spellcastingClient struct {
		basicsProvider api.BasicsProvider
	}
)

type SpellcastingClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*SpellcastingDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SpellcastingClient {
	return &spellcastingClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *spellcastingClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *spellcastingClient) GetByIndex(index string) (*SpellcastingDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := SpellcastingDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
