// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: monsters
// Endpoint: monsters
// API Name: Monster
// LC API Name: monster
// API Class: MonsterDetail

package monsters

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	monsterClient struct {
		api.BasicsProvider
		uri string
	}
)

type MonsterClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*MonsterDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) MonsterClient {
	return &monsterClient{
		BasicsProvider: basicsProvider,
		uri: "/monsters",
	}
}

func (ac *monsterClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *monsterClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *monsterClient) GetByIndex(index string) (*MonsterDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := MonsterDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
