// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: monsters
// Endpoint: monsters
// API Name: Monster
// LC API Name: monster
// API Class: MonsterDetail

package monsters

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/monsters"
	ChildEndpoint = Endpoint + "/"
)

type (
	monsterClient struct {
		basicsProvider api.BasicsProvider
	}
)

type MonsterClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*MonsterDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) MonsterClient {
	return &monsterClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *monsterClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *monsterClient) GetByIndex(index string) (*MonsterDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := MonsterDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
