// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: proficiencies
// Endpoint: proficiencies
// API Name: Proficiency
// LC API Name: proficiency
// API Class: ProficiencyDetail

package proficiencies

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	proficiencyClient struct {
		api.BasicsProvider
		uri string
	}
)

type ProficiencyClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*ProficiencyDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) ProficiencyClient {
	return &proficiencyClient{
		BasicsProvider: basicsProvider,
		uri: "/proficiencies",
	}
}

func (ac *proficiencyClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *proficiencyClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *proficiencyClient) GetByIndex(index string) (*ProficiencyDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := ProficiencyDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
