// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: languages
// Endpoint: languages
// API Name: Language
// LC API Name: language
// API Class: LanguageDetail

package languages

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/languages"
	ChildEndpoint = Endpoint + "/"
)

type (
	languageClient struct {
		basicsProvider api.BasicsProvider
	}
)

type LanguageClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*LanguageDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) LanguageClient {
	return &languageClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *languageClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *languageClient) GetByIndex(index string) (*LanguageDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := LanguageDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
