// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: weapon_properties
// Endpoint: weapon-properties
// API Name: WeaponProperties
// LC API Name: weaponProperties
// API Class: api.Description

package weapon_properties

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/weapon-properties"
	ChildEndpoint = Endpoint + "/"
)

type (
	weaponPropertiesClient struct {
		basicsProvider api.BasicsProvider
	}
)

type WeaponPropertiesClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*api.Description, error)
}

func NewClient(basicsProvider api.BasicsProvider) WeaponPropertiesClient {
	return &weaponPropertiesClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *weaponPropertiesClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *weaponPropertiesClient) GetByIndex(index string) (*api.Description, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := api.Description{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
