// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: weapon_properties
// Endpoint: weapon-properties
// API Name: WeaponProperties
// LC API Name: weaponProperties
// API Class: WeaponPropertiesDetail

package weapon_properties

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	weaponPropertiesClient struct {
		api.BasicsProvider
		uri string
	}
)

type WeaponPropertiesClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*WeaponPropertiesDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) WeaponPropertiesClient {
	return &weaponPropertiesClient{
		BasicsProvider: basicsProvider,
		uri: "/weapon-properties",
	}
}

func (ac *weaponPropertiesClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *weaponPropertiesClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *weaponPropertiesClient) GetByIndex(index string) (*WeaponPropertiesDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := WeaponPropertiesDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
