// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: classes
// Endpoint: classes
// API Name: Class
// LC API Name: class
// API Class: ClassDetail

package classes

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	classClient struct {
		api.BasicsProvider
		uri string
	}
)

type ClassClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*ClassDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) ClassClient {
	return &classClient{
		BasicsProvider: basicsProvider,
		uri: "/classes",
	}
}

func (ac *classClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *classClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *classClient) GetByIndex(index string) (*ClassDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := ClassDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
