// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: classes
// Endpoint: classes
// API Name: Class
// LC API Name: class

package classes

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/classes"
	ChildEndpoint = Endpoint + "/"
)

type (
	classClient struct {
		basicsProvider api.BasicsProvider
	}
)

type ClassClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*ClassDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) ClassClient {
	return &classClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *classClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *classClient) GetByIndex(index string) (*ClassDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := ClassDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
