// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: skills
// Endpoint: skills
// API Name: Skill
// LC API Name: skill
// API Class: SkillDetail

package skills

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	skillClient struct {
		api.BasicsProvider
		uri string
	}
)

type SkillClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*SkillDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SkillClient {
	return &skillClient{
		BasicsProvider: basicsProvider,
		uri: "/skills",
	}
}

func (ac *skillClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *skillClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *skillClient) GetByIndex(index string) (*SkillDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := SkillDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
