// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: skills
// Endpoint: skills
// API Name: Skill
// LC API Name: skill
// API Class: SkillDetail

package skills

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/skills"
	ChildEndpoint = Endpoint + "/"
)

type (
	skillClient struct {
		basicsProvider api.BasicsProvider
	}
)

type SkillClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*SkillDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SkillClient {
	return &skillClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *skillClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *skillClient) GetByIndex(index string) (*SkillDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := SkillDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
