// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: subraces
// Endpoint: subraces
// API Name: Subrace
// LC API Name: subrace
// API Class: SubraceDetail

package subraces

import (
	"encoding/json"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/subraces"
	ChildEndpoint = Endpoint + "/"
)

type (
	subraceClient struct {
		basicsProvider api.BasicsProvider
	}
)

type SubraceClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*SubraceDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SubraceClient {
	return &subraceClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *subraceClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *subraceClient) GetByIndex(index string) (*SubraceDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := SubraceDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
