// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: subraces
// Endpoint: subraces
// API Name: Subrace
// LC API Name: subrace
// API Class: SubraceDetail

package subraces

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	subraceClient struct {
		api.BasicsProvider
		uri string
	}
)

type SubraceClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*SubraceDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SubraceClient {
	return &subraceClient{
		BasicsProvider: basicsProvider,
		uri: "/subraces",
	}
}

func (ac *subraceClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *subraceClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *subraceClient) GetByIndex(index string) (*SubraceDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := SubraceDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
