// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: races
// Endpoint: races
// API Name: Race
// LC API Name: race
// API Class: RaceDetail

package races

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	raceClient struct {
		api.BasicsProvider
		uri string
	}
)

type RaceClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*RaceDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) RaceClient {
	return &raceClient{
		BasicsProvider: basicsProvider,
		uri: "/races",
	}
}

func (ac *raceClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *raceClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *raceClient) GetByIndex(index string) (*RaceDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := RaceDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
