// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: races
// Endpoint: races
// API Name: Race
// LC API Name: race
// API Class: RaceDetail

package races

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/races"
	ChildEndpoint = Endpoint + "/"
)

type (
	raceClient struct {
		basicsProvider api.BasicsProvider
	}
)

type RaceClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*RaceDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) RaceClient {
	return &raceClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *raceClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *raceClient) GetByIndex(index string) (*RaceDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := RaceDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
