// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: subclasses
// Endpoint: subclasses
// API Name: Subclass
// LC API Name: subclass
// API Class: SubclassDetail

package subclasses

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/subclasses"
	ChildEndpoint = Endpoint + "/"
)

type (
	subclassClient struct {
		basicsProvider api.BasicsProvider
	}
)

type SubclassClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*SubclassDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SubclassClient {
	return &subclassClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *subclassClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *subclassClient) GetByIndex(index string) (*SubclassDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := SubclassDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
