// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: subclasses
// Endpoint: subclasses
// API Name: Subclass
// LC API Name: subclass
// API Class: SubclassDetail

package subclasses

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	subclassClient struct {
		api.BasicsProvider
		uri string
	}
)

type SubclassClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*SubclassDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SubclassClient {
	return &subclassClient{
		BasicsProvider: basicsProvider,
		uri: "/subclasses",
	}
}

func (ac *subclassClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *subclassClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *subclassClient) GetByIndex(index string) (*SubclassDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := SubclassDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
