// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: equipment
// Endpoint: equipment
// API Name: Equipment
// LC API Name: equipment
// API Class: EquipmentDetail

package equipment

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	equipmentClient struct {
		api.BasicsProvider
		uri string
	}
)

type EquipmentClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*EquipmentDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) EquipmentClient {
	return &equipmentClient{
		BasicsProvider: basicsProvider,
		uri: "/equipment",
	}
}

func (ac *equipmentClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *equipmentClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *equipmentClient) GetByIndex(index string) (*EquipmentDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := EquipmentDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
