// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: traits
// Endpoint: traits
// API Name: Trait
// LC API Name: trait
// API Class: TraitDetail

package traits

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/traits"
	ChildEndpoint = Endpoint + "/"
)

type (
	traitClient struct {
		basicsProvider api.BasicsProvider
	}
)

type TraitClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*TraitDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) TraitClient {
	return &traitClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *traitClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *traitClient) GetByIndex(index string) (*TraitDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := TraitDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
