// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: features
// Endpoint: features
// API Name: Feature
// LC API Name: feature
// API Class: FeatureDetail

package features

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/features"
	ChildEndpoint = Endpoint + "/"
)

type (
	featureClient struct {
		basicsProvider api.BasicsProvider
	}
)

type FeatureClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*FeatureDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) FeatureClient {
	return &featureClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *featureClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *featureClient) GetByIndex(index string) (*FeatureDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := FeatureDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
