// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: features
// Endpoint: features
// API Name: Feature
// LC API Name: feature
// API Class: FeatureDetail

package features

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	featureClient struct {
		api.BasicsProvider
		uri string
	}
)

type FeatureClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*FeatureDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) FeatureClient {
	return &featureClient{
		BasicsProvider: basicsProvider,
		uri: "/features",
	}
}

func (ac *featureClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *featureClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *featureClient) GetByIndex(index string) (*FeatureDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := FeatureDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
