// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: starting_equipment
// Endpoint: starting-equipment
// API Name: StartingEquipment
// LC API Name: startingEquipment
// API Class: StartingEquipmentDetail

package starting_equipment

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

const (
	// Endpoints for ability scores
	Endpoint      = "/starting-equipment"
	ChildEndpoint = Endpoint + "/"
)

type (
	startingEquipmentClient struct {
		basicsProvider api.BasicsProvider
	}
)

type StartingEquipmentClient interface {
	GetList() (*api.ListResponse, error)
	GetByIndex(index string) (*StartingEquipmentDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) StartingEquipmentClient {
	return &startingEquipmentClient{
		basicsProvider: basicsProvider,
	}
}

func (ac *startingEquipmentClient) GetList() (*api.ListResponse, error) {
	return ac.basicsProvider.GetListForUrl(Endpoint)
}

func (ac *startingEquipmentClient) GetByIndex(index string) (*StartingEquipmentDetail, error) {
	result, err := ac.basicsProvider.ApiGet(ChildEndpoint + index)
	if err != nil {
		return nil, err
	}

	d := StartingEquipmentDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
