// This file is generated by go-dnd5eapi/gen/api_gen.go.  DO NOT EDIT THIS FILE.  Generation parameters are:
// Package Name: spells
// Endpoint: spells
// API Name: Spell
// LC API Name: spell
// API Class: SpellDetail

package spells

import (
	json "github.com/json-iterator/go"

	"github.com/kjkondratuk/go-dnd5eapi/api"
)

type (
	spellClient struct {
		api.BasicsProvider
		uri string
	}
)

type SpellClient interface {
	GetList() (*api.ListResponse, error)
	QueryList(query map[string]string) (*api.ListResponse, error)
	GetByIndex(index string) (*SpellDetail, error)
}

func NewClient(basicsProvider api.BasicsProvider) SpellClient {
	return &spellClient{
		BasicsProvider: basicsProvider,
		uri: "/spells",
	}
}

func (ac *spellClient) GetList() (*api.ListResponse, error) {
	return ac.GetListForUrl(ac.uri)
}

func (ac *spellClient) QueryList(query map[string]string) (*api.ListResponse, error) {
	return ac.QueryListForUrl(ac.uri, query)
}

func (ac *spellClient) GetByIndex(index string) (*SpellDetail, error) {
	result, err := ac.ApiGet(ac.uri + "/" + index)
	if err != nil {
		return nil, err
	}

	d := SpellDetail{}
	err = json.Unmarshal(result, &d)
	if err != nil {
		return nil, err
	}
	return &d, nil
}
